# Generated by Django 4.2.11 on 2024-04-25 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=64)),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ListTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.CharField(max_length=256)),
                ('public', models.BooleanField(default=False)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tierlist.user')),
            ],
        ),
        migrations.CreateModel(
            name='ListPublished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.CharField(max_length=256)),
                ('public', models.BooleanField(default=False)),
                ('s_tier', models.TextField()),
                ('a_tier', models.TextField()),
                ('b_tier', models.TextField()),
                ('c_tier', models.TextField()),
                ('d_tier', models.TextField()),
                ('f_tier', models.TextField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tierlist.user')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image_url', models.TextField()),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tierlist.listtemplate')),
            ],
        ),
    ]
