# Generated by Django 4.2.11 on 2024-08-22 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('image_url', models.TextField(blank=True, default='', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'tierforge.user',
            },
        ),
        migrations.CreateModel(
            name='ListTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('background_image_url', models.TextField(blank=True, default='', null=True)),
                ('public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tierforge.listtemplate',
            },
        ),
        migrations.CreateModel(
            name='ListPublished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('public', models.BooleanField(default=False)),
                ('s_tier', models.TextField(default='[]')),
                ('a_tier', models.TextField(default='[]')),
                ('b_tier', models.TextField(default='[]')),
                ('c_tier', models.TextField(default='[]')),
                ('d_tier', models.TextField(default='[]')),
                ('f_tier', models.TextField(default='[]')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='published_lists', to='tierlist.listtemplate')),
            ],
            options={
                'db_table': 'tierforge.listpublished',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image_url', models.TextField(blank=True, null=True)),
                ('list', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tierlist.listtemplate')),
            ],
            options={
                'db_table': 'tierforge.card',
            },
        ),
    ]
