# Generated by Django 4.2.11 on 2024-05-03 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tierlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='list_id',
        ),
        migrations.AddField(
            model_name='card',
            name='list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tierlist.listtemplate'),
        ),
        migrations.AlterField(
            model_name='listpublished',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='published_lists', to='tierlist.listtemplate'),
        ),
    ]
