# Generated by Django 4.2.11 on 2024-08-22 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tierlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='card',
            table='tierforge.card',
        ),
        migrations.AlterModelTable(
            name='listpublished',
            table='tierforge.listpublished',
        ),
        migrations.AlterModelTable(
            name='listtemplate',
            table='tierforge.listtemplate',
        ),
        migrations.AlterModelTable(
            name='user',
            table='tierforge.user',
        ),
    ]
