# Generated by Django 4.2.11 on 2024-05-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierlist', '0002_remove_card_list_id_card_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtemplate',
            name='background_image_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
