# Generated by Django 4.2.11 on 2024-06-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierlist', '0003_listtemplate_background_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listpublished',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='listtemplate',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
