# Generated by Django 4.2.11 on 2024-08-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierlist', '0004_alter_listpublished_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
